language: node_js
node_js:
- 6.11.5
cache:
  directories:
  - functions/node_modules
before_install:
  - npm i -g npm
deploy:
  provider: firebase
  token:
    secure: Xtx8rnrw+rR77jqFwUfOkSp/DEIw0X8qSLb9LDoz78FW8r2l3oJaeTx6LQIeFnIDFr0YYlUyGAJptAbLqcJlReSev9qSEkycjdQakG9EF5xB26lNjDFAm9T/Q1Va5dk5EZ+4QocsmE32/Q+H9hVbEFn0rQbsq6wXhr03sYkiGBYMx+qRmSLA5U5Q8tOR3usieZB2Cy+MaAkBCJql4DpfeZcWkjdfrHJ8mDkW0d4rnwc/wfYjpYWY0tYgIkvOKLq8az9Ae8T5gQ5D/u+Zu6jonvz1PqpJksFY8tyyb4vYpCcqEx0k7T+hIQOXC7lfb5UacZQsMu5rXQNb18x8CvpJKTng+a/Jdv2mE1qopHiV/E8p8QvAiINEmkdnlUbsxdP0wZOmZzZaQ3M7OHXRR+4oUz6am3XQF54j3jmgFzEfXNs5JJgNW/HuiSFG2hqrHPQTZJKW0qqNteCwKBGEJU3GMxgABOkcOawX2mgRZzRDhHG1c7W4rgR5XvGIHwXqpIIw5TIIrCKDxxKBYeQ7lTuP5iKVeQOf+OTj+iiWyavYeQTBiX5UIgkWSf9KgbgSMPWZsUAbnXBk59GSn9rWg9R5MGQIjXWSyJSPuLqF50xeqx3pxddo+v6ujIGIqnT4GffAVa50WtjHoXa/1XPVQoAn26px89Ux3CP9vBicJbRg7hM=
  project: vanilla-pwa
